# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'taxiguber' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for taxiguber

  target 'taxiguber-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'taxiguberTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'taxiguber-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for taxiguber-tvOS

  target 'taxiguber-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
